config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  resources :companies, only: [:new, :edit, :update, :create]
  resources :positions
  resources :applicants, only: [:index, :new, :create]
  
  get "vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brazil.rb
class Brazil
    def self.states
        {
            'AC': 'Acre',
            'AL': 'Alagoas',
            'AP': 'Amapá',
            'AM': 'Amazonas',
            'BA': 'Bahia',
            'CE': 'Ceará',
            'DF': 'Distrito Federal',
            'ES': 'Espírito Santo',
            'GO': 'Goiás',
            'MA': 'Maranhão',
            'MT': 'Mato Grosso',
            'MS': 'Mato Grosso do Sul',
            'MG': 'Minas Gerais',
            'PA': 'Pará',
            'PB': 'Paraíba',
            'PR': 'Paraná',
            'PE': 'Pernambuco',
            'PI': 'Piauí',
            'RJ': 'Rio de Janeiro',
            'RN': 'Rio Grande do Norte',
            'RS': 'Rio Grande do Sul',
            'RO': 'Rondônia',
            'RR': 'Roraima',
            'SC': 'Santa Catarina',
            'SP': 'São Paulo',
            'SE': 'Sergipe',
            'TO': 'Tocantins',
        }
    end

end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions
  has_one_attached :logo
  validates :trading_name, :domain, :address, :cnpj, presence: true
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company

  enum career: [:developer, :business_inteligence, :information_technology, :design, 
                :product, :technology, :other]
  enum contract: [:clt, :pj, :match]

  enum levels: [:junior, :middle, :senior]

  has_rich_text :requirements

  validates :name, :career, :contract, :level, :city, :state, :summary, :requirements,
            :remuneration, :expiration_date, :spots_available, presence: true


end                                   

app/models/user.rb
class User < ApplicationRecord


  # calls: user.admin? user.admin! user.role user.user? user.vip?
  enum role: {user: 0, vip: 1, admin: 2}
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  
  validates :email, presence: true
  validate :email_cant_be_personal

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :company

  def email_cant_be_personal 
    if PERSONAL_DOMAINS.any? { |domain| email.end_with?(domain)}
      errors.add(:email, 'Não é e-mail corporativo')
    end
  end


end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = current_user.build_company
  end

  def edit
    @company = current_user.company
  end

  def create
    @company = current_user.build_company(company_params)
    if @company.save
      flash[:notice] = 'Empresa cadastrada com sucesso.'
      redirect_to root_path
    else
      flash[:error] = 'Erro ao cadastrar a empresa.'
      render :new
    end
  end

  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = 'Empresa atualizada com sucesso.'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :address, :cnpj, :domain, :logo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Position.ransack(params[:q])
    @positions = @q.result.page(params[:page]).per(params[:per])
    @contracts = [ ['CLT', 0],['JP',1],['Match',2] ]
    @levels = [ ['Junior', 0],['Middle',1],['Senior',2] ]
    @teams = [ ['e-commerce', 0],['front-end',1],['back-end',2], ['suporte ao cliente',3], ['DBA',4], ['devops',5] ]
    @technologies = [ ['Java', 0],['C#',1],['Ruby',2], ['React',3], ['Node',4] ]
    
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts
  before_action :set_position, only: [:edit, :show, :update]

  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def edit
  end

  def show
  end

  def create
    @position = @company.positions.new(params_position)
    if @position.save
      flash[:success] = 'Vaga cadastrada com sucesso.'
      redirect_to positions_path
    else
      render :new
    end
  end

  def update
    if @position.update(params_position)
      redirect_to positions_path
    else
      render :edit
    end
  end

  private

  def set_position
    @position = @company.positions.find(params[:id])
  end

  def params_position
    params.require(:position).permit(:name, :career, :contract, :level, :remote, :publish, :city, :state, :summary, :requirements,
                                    :remuneration, :technology, :team, :expiration_date, :spots_available )
  end

  def set_company
    redirect_to new_company_path if current_user.company.nil?
    @company = current_user.company
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
  end

  def set_i18n_contracts
    @contracts = I18n.t('activerecord.attributes.position.contracts')
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def dynamic_url_company
    if current_user.company.present? && current_user.company.try(:id).present?
      edit_company_path(current_user.company)
    else
      new_company_path
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
    def text_position(position)
        "A empresa #{position.company.name} em #{position.city} está com a vaga de #{position.name}. Veja mais detalhes no nosso mural! #{url_position(position)}"
    end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/applicants/index.html.haml
%h1 Applicants#index
%p Find me in app/views/applicants/index.html.haml

app/views/applicants/new.html.haml
%h1 Applicants#new
%p Find me in app/views/applicants/new.html.haml

app/views/companies/_form.html.haml
= simple_form_for @company do |f|
  = f.input :trading_name
  = f.input :domain
  = f.input :address
  = f.input :cnpj
  = image_tag(url_for(@company.logo), class: 'company-logo') unless @company.new_record? && !@company.logo.nil?
  = f.input :logo
  = f.button :submit, class: 'btn btn-primary'

app/views/companies/edit.html.haml
%h2 Minha Empresa
= render 'form'

app/views/companies/new.html.haml
%h2 Cadastrar Empresa
= render 'form'

app/views/home/index.html.haml
%header.text-center
  %h1 Hyper Vagas
  %p Anúncios na Área de Tecnologia

= search_form_for @q, url: root_path do |f|
  .row
    .col-sm
      .form-group
        =f.label :trading_name_cont, "Empresa"
        =f.search_field :name_cont, class: "form-control"
    .col-sm
      .form-group
        =f.label :name_cont, "Nome da vaga"
        =f.search_field :name_cont, class: "form-control"
    .col-sm
      .form-group
        =f.label :contract_eq, "Modalidade de contrato"
        =f.select :contract_eq, options_from_collection_for_select(@contracts, :second, :first, @q.contract_eq), {include_blank: true}, {class: "form-control"}
    .col-sm
      .form-group
        =f.label :state_eq, "Estado"
        =f.select :state_eq, options_from_collection_for_select(Brazil.states, :first, :second, @q.state_eq), {include_blank: true}, {class: "form-control"}
    .col-sm
      %button.btn.btn-danger{:type => "submit", style: 'margin-top: 31px;'} Pesquisar


- @positions.each do |position|
  = render position

%p.d-block.text-center.mt-3
  .text-center= paginate @positions, theme: 'twitter-bootstrap-4', default_per_page: 5

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title Hyper Vagas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/topbar'
    %main.container{:role => "main"}
      = yield
    %footer
      %p Sistema desenvolvido por Ricardo Caselli
      %p= "Desde #{Time.new.year}"

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title Hyper Vagas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #logreg-forms
      = yield

app/views/positions/_form.html.haml
= simple_form_for @position do |f|
  = f.input :name
  = f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @position.career
  = f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @position.contract
  = f.input :level, as: :select, collection: @levels, label_method: :second, value_method: :first, include_blank: false, selected: @position.level
  = f.input :remote
  = f.input :publish
  = f.input :city
  = f.input :state, as: :select, collection: Brazil.states, label_method: :second, value_method: :first
  = f.input :summary, maxlength: 360, input_html: { class: 'count-textarea', rows: 4 }
  = f.input :remuneration
  = f.input :requirements
  = f.input :technology, as: :select, collection: @technologies, multiple: true, include_blank: false
  = f.input :team, as: :select, collection: @teams, multiple: true, include_blank: false
  = f.input :expiration_date
  = f.input :spots_available

  #the-count
    %span#current 0
    %span#maximun / 360
  %label Descrição
  = f.rich_text_area :description
  = f.button :submit, class: 'btn btn-primary'

app/views/positions/_position.html.haml
.card.card-position
  .card-body
    .container.conteiner-card
      .row
        .col-2
          = image_tag position.company.logo, alt: "Logomarca da empresa #{position.company.name}", class: 'card-img-top'
        .col-10
          %h4= position.name
          %h5= "#{I18n.t('activerecord.attributes.position.careers')[position.career.to_s]} - #{position.city} - #{I18n.t('activerecord.attributes.position.contracts')[position.contract.to_s]}"
          %p empty
          .row
            .col-sm.mt-3
              %button.btn.btn-danger{:type => "button"} Ver mais
              %button.btn.btn-success{:type => "button"} Candidatar-se
            .col-sm.text-right.mt-3.group-social-network
              = link_to(image_tag('social-network/linkedin.svg', :alt => 'Ícone do LinkedIn', :height => '32', :width => '32'), "https://www.linkedin.com/sharing/share-offsite/?url=#{url_position(position)}")
              = link_to(image_tag('social-network/whatsapp.svg', :alt => 'Ícone do Whatsapp', :height => '32', :width => '32'), "https://wa.me/?text=#{text_position(position)}")
              = link_to(image_tag('social-network/twitter.svg', :alt => 'Ícone do Twitter', :height => '32', :width => '32'), "https://twitter.com/intent/tweet?text=#{text_position(position)}")
              

app/views/positions/edit.html.haml
%h2 Editar vaga
= render 'form'

app/views/positions/index.html.haml
%h2 Minhas vagas

%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Título
      %th{:scope => "col"} Carreira
      %th{:scope => "col"} Local
      %th{:scope => "col"} Tipo de contrato
      %th{:scope => "col"} Candidaturas
      %th{:scope => "col"} Ações


      
  %tbody
    - @positions.each do |position|
      %tr
        %th{:scope => "row"}= position.name
        %td= position.career
        %td= position.remote # aplicar helper
        %td= position.contract
        %td 1 (ver detalhes)
        %td
          = link_to 'Editar', edit_position_path(position)

app/views/positions/new.html.haml
%h2 Publica vaga
= render 'form'

app/views/positions/show.html.haml
%h1 Positions#show
%p Find me in app/views/positions/show.html.haml

app/views/shared/_topbar.html.haml
%nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} Hyper Vagas
  %button.navbar-toggler.p-0.border-0{"data-toggle" => "offcanvas", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExampleDefault.navbar-collapse.offcanvas-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => root_path}
          Inicio
          %span.sr-only (current)
      - unless user_signed_in?
        %li.nav-item
          = link_to 'Login/Cadastro', new_user_session_path, class: 'nav-link'
      - if user_signed_in?
        %li.nav-item.active
          %a.nav-link{:href => dynamic_url_company}
            Empresa
        %li.nav-item.active
          %a.nav-link{:href => positions_url}
            Minhas vagas
        %li.nav-item.dropdown
          %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"} Configurações
          .dropdown-menu{"aria-labelledby" => "dropdown01"}
            = link_to('Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item')
        %li.nav-item
          %a.nav-link.public-position{:href => new_position_path}
            Publicar vaga